spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qliina_db
    username: root_user
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    com.jjenus.qliina_management: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR

server:
  port: 8080
  
# Encryption Configuration
encryption:
  secret: ${ENCRYPTION_SECRET:tWHKe8dL9FTumZynTVF8UDYruDUiODdOh0WWLt7fY0I=}
  salt: ${ENCRYPTION_SALT:f14ecc5ca42ba522a1f5a38df1564282}
  iteration-count: 65536
  key-length: 256
  enabled: true

